# Generated by Django 2.2.7 on 2019-12-07 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DQ_FAILURE',
            fields=[
                ('dq_failure_id', models.AutoField(primary_key=True, serialize=False)),
                ('batchid', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('business_rule', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('dq_dimension', models.CharField(max_length=255)),
                ('column_value', models.CharField(max_length=255)),
                ('fixed_yn', models.CharField(max_length=255)),
                ('fixed_date', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=255)),
                ('error_code', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('master_load_id', models.IntegerField()),
                ('transaction_date', models.DateTimeField()),
                ('alt_error_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('locationid', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('state_prov_code', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('time_zone_gid', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_type', models.CharField(max_length=255)),
                ('locode', models.CharField(max_length=255)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('duns', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('pickup_time_start', models.CharField(max_length=255)),
                ('pickup_time_end', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=255)),
                ('zip_city', models.CharField(max_length=255)),
                ('location_office_type', models.CharField(max_length=255)),
                ('alternate_duns', models.CharField(max_length=255)),
                ('cisco_code', models.CharField(max_length=255)),
                ('plant_code_2_letter', models.CharField(max_length=255)),
                ('alternate_pk', models.IntegerField()),
                ('batchid', models.CharField(max_length=255)),
                ('record_status', models.CharField(max_length=255)),
                ('message_tx', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('drc_supplier_load', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('schedule_date', models.DateTimeField()),
                ('pickup_volume', models.FloatField()),
                ('loading_time_per_ton_in_mins', models.FloatField()),
                ('filter_status', models.CharField(max_length=255)),
                ('alt_location_name', models.CharField(max_length=255)),
                ('logistics_type', models.CharField(max_length=255)),
                ('billing_cisco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='BH_GM_DOCK',
            fields=[
                ('bh_gm_dock_id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_cisco', models.IntegerField(blank=True, null=True)),
                ('location_code', models.CharField(blank=True, max_length=255, null=True)),
                ('duns', models.IntegerField(blank=True, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('dock_code', models.CharField(max_length=255)),
                ('simplified_dock', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_shifts', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('drop_deck_allowed_yn', models.BooleanField(blank=True, null=True)),
                ('dock_bump_yn', models.BooleanField(blank=True, null=True)),
                ('max_dock_bumps_allowed', models.IntegerField(blank=True, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('co_locate', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabledata.Location')),
            ],
            options={
                'verbose_name': 'BH_GM_DOCK',
                'verbose_name_plural': 'BH_GM_DOCKS',
            },
        ),
    ]
