# Generated by Django 2.2.7 on 2019-12-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bh_gm_dock',
            name='billing_cisco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bh_gm_dock',
            name='duns',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
