# Generated by Django 2.1.12 on 2020-01-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabledata', '0002_auto_20191216_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='BH_GM_Constraint_Dock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bh_compatible_dock_id', models.IntegerField()),
                ('bh_origin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabledata.BH_GM_DOCK')),
            ],
        ),
    ]
