# Generated by Django 2.1.15 on 2020-01-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledata', '0003_bh_gm_constraint_dock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_map_id', models.IntegerField(db_column='CODE_MAP_ID')),
                ('type', models.CharField(blank=True, db_column='TYPE', max_length=50, null=True)),
                ('input_value', models.CharField(blank=True, db_column='INPUT_VALUE', max_length=100, null=True)),
                ('output_value', models.CharField(blank=True, db_column='OUTPUT_VALUE', max_length=100, null=True)),
                ('display_label', models.CharField(blank=True, db_column='DISPLAY_LABEL', max_length=100, null=True)),
            ],
            options={
                'db_table': 'CODEMAP',
            },
        ),
    ]
