# Generated by Django 2.1.12 on 2019-11-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20191105_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='organization',
            new_name='OrgName',
        ),
    ]
